# Generated by Django 4.2.11 on 2024-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslots',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
